version: '3'

services:

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: optimus
      POSTGRES_PASSWORD: P1ssw0rd
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data